
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: securityrules.azure.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=='Ready')].status
    name: READY
    type: string
  - JSONPath: .status.conditions[?(@.type=='Synced')].status
    name: SYNCED
    type: string
  - JSONPath: .status.state
    name: STATE
    type: string
  - JSONPath: .spec.location
    name: LOCATION
    type: string
  - JSONPath: .spec.reclaimPolicy
    name: RECLAIM-POLICY
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: azure.crossplane.io
  names:
    categories:
    - crossplane
    - managed
    - azure
    kind: SecurityRule
    listKind: SecurityRuleList
    plural: securityrules
    singular: securityrule
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SecurityRule network security rule.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        etag:
          description: Etag - A unique read-only string that changes whenever the
            resource is updated.
          type: string
        id:
          description: ID - Resource ID.
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        name:
          description: Name - The name of the resource that is unique within a resource
            group. This name can be used to access the resource.
          type: string
        properties:
          description: SecurityRulePropertiesFormat - Properties of the security rule.
          properties:
            access:
              description: 'Access - The network traffic is allowed or denied. Possible
                values include: ''SecurityRuleAccessAllow'', ''SecurityRuleAccessDeny'''
              type: string
            description:
              description: Description - A description for this rule. Restricted to
                140 chars.
              type: string
            destinationAddressPrefix:
              description: DestinationAddressPrefix - The destination address prefix.
                CIDR or destination IP range. Asterisk '*' can also be used to match
                all source IPs. Default tags such as 'VirtualNetwork', 'AzureLoadBalancer'
                and 'Internet' can also be used.
              type: string
            destinationAddressPrefixes:
              description: DestinationAddressPrefixes - The destination address prefixes.
                CIDR or destination IP ranges.
              items:
                type: string
              type: array
            destinationApplicationSecurityGroups:
              description: DestinationApplicationSecurityGroups - The application
                security group specified as destination.
              items:
                description: ApplicationSecurityGroup an application security group
                  in a resource group.
                properties:
                  etag:
                    description: Etag - READ-ONLY; A unique read-only string that
                      changes whenever the resource is updated.
                    type: string
                  id:
                    description: ID - Resource ID.
                    type: string
                  location:
                    description: Location - Resource location.
                    type: string
                  name:
                    description: Name - READ-ONLY; Resource name.
                    type: string
                  properties:
                    description: ApplicationSecurityGroupPropertiesFormat - Properties
                      of the application security group.
                    properties:
                      provisioningState:
                        description: 'ProvisioningState - READ-ONLY; The provisioning
                          state of the application security group resource. Possible
                          values are: ''Succeeded'', ''Updating'', ''Deleting'', and
                          ''Failed''.'
                        type: string
                      resourceGuid:
                        description: ResourceGUID - READ-ONLY; The resource GUID property
                          of the application security group resource. It uniquely
                          identifies a resource, even if the user changes its name
                          or migrate the resource across subscriptions or resource
                          groups.
                        type: string
                    type: object
                  type:
                    description: Type - READ-ONLY; Resource type.
                    type: string
                type: object
              type: array
            destinationPortRange:
              description: DestinationPortRange - The destination port or range. Integer
                or range between 0 and 65535. Asterisk '*' can also be used to match
                all ports.
              type: string
            destinationPortRanges:
              description: DestinationPortRanges - The destination port ranges.
              items:
                type: string
              type: array
            direction:
              description: 'Direction - The direction of the rule. The direction specifies
                if rule will be evaluated on incoming or outgoing traffic. Possible
                values include: ''SecurityRuleDirectionInbound'', ''SecurityRuleDirectionOutbound'''
              type: string
            priority:
              description: Priority - The priority of the rule. The value can be between
                100 and 4096. The priority number must be unique for each rule in
                the collection. The lower the priority number, the higher the priority
                of the rule.
              format: int32
              type: integer
            protocol:
              description: 'Protocol - Network protocol this rule applies to. Possible
                values include: ''SecurityRuleProtocolTCP'', ''SecurityRuleProtocolUDP'',
                ''SecurityRuleProtocolIcmp'', ''SecurityRuleProtocolEsp'', ''SecurityRuleProtocolAsterisk'''
              type: string
            provisioningState:
              description: 'ProvisioningState - The provisioning state of the public
                IP resource. Possible values are: ''Updating'', ''Deleting'', and
                ''Failed''.'
              type: string
            sourceAddressPrefix:
              description: SourceAddressPrefix - The CIDR or source IP range. Asterisk
                '*' can also be used to match all source IPs. Default tags such as
                'VirtualNetwork', 'AzureLoadBalancer' and 'Internet' can also be used.
                If this is an ingress rule, specifies where network traffic originates
                from.
              type: string
            sourceAddressPrefixes:
              description: SourceAddressPrefixes - The CIDR or source IP ranges.
              items:
                type: string
              type: array
            sourceApplicationSecurityGroups:
              description: SourceApplicationSecurityGroups - The application security
                group specified as source.
              items:
                description: ApplicationSecurityGroup an application security group
                  in a resource group.
                properties:
                  etag:
                    description: Etag - READ-ONLY; A unique read-only string that
                      changes whenever the resource is updated.
                    type: string
                  id:
                    description: ID - Resource ID.
                    type: string
                  location:
                    description: Location - Resource location.
                    type: string
                  name:
                    description: Name - READ-ONLY; Resource name.
                    type: string
                  properties:
                    description: ApplicationSecurityGroupPropertiesFormat - Properties
                      of the application security group.
                    properties:
                      provisioningState:
                        description: 'ProvisioningState - READ-ONLY; The provisioning
                          state of the application security group resource. Possible
                          values are: ''Succeeded'', ''Updating'', ''Deleting'', and
                          ''Failed''.'
                        type: string
                      resourceGuid:
                        description: ResourceGUID - READ-ONLY; The resource GUID property
                          of the application security group resource. It uniquely
                          identifies a resource, even if the user changes its name
                          or migrate the resource across subscriptions or resource
                          groups.
                        type: string
                    type: object
                  type:
                    description: Type - READ-ONLY; Resource type.
                    type: string
                type: object
              type: array
            sourcePortRange:
              description: SourcePortRange - The source port or range. Integer or
                range between 0 and 65535. Asterisk '*' can also be used to match
                all ports.
              type: string
            sourcePortRanges:
              description: SourcePortRanges - The source port ranges.
              items:
                type: string
              type: array
          type: object
      type: object
  version: v1alpha3
  versions:
  - name: v1alpha3
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
